LIBRARY IEEE;
USE IEEE.STD_LOGIC_1164.ALL;

PACKAGE PAQUETES IS

COMPONENT P2
PORT (CLKOUT,PRE,CLR,S,R,T,D,J,K : IN STD_LOGIC;
		SEL: IN STD_LOGIC_VECTOR(1 DOWNTO 0);
		Q,NQ : INOUT STD_LOGIC
	);
END COMPONENT;
COMPONENT DIV PORT
(
    CLK:    IN  STD_LOGIC;
    CLKOUT: OUT STD_LOGIC;
    LED    : OUT STD_LOGIC 
);
END COMPONENT;
END PAQUETES;
