LIBRARY IEEE;
USE IEEE.STD_LOGIC_1164.ALL;
LIBRARY WORK;
USE WORK.PAQUETES.ALL;

ENTITY TOPLEVEL IS
    PORT(
        PRE, CLR, S, R, T, D, J, K : IN STD_LOGIC;
        SEL  : IN  STD_LOGIC_VECTOR(1 DOWNTO 0);
        Q, NQ : INOUT STD_LOGIC;
        LED  : OUT STD_LOGIC;
        CLK  : IN  STD_LOGIC
    );
END ENTITY;

ARCHITECTURE A_TOPLEVEL OF TOPLEVEL IS
    SIGNAL CLKOUT : STD_LOGIC;
BEGIN
    U0 : P2  PORT MAP (CLKOUT, PRE, CLR, S, R, T, D, J, K, SEL, Q, NQ);
    U1 : DIV PORT MAP (CLK => CLK, CLKOUT => CLKOUT, LED => LED);
END A_TOPLEVEL;