LIBRARY IEEE;
USE IEEE.STD_LOGIC_1164.ALL;
USE IEEE.STD_LOGIC_ARITH.ALL;
USE IEEE.STD_LOGIC_UNSIGNED.ALL;

ENTITY CD IS PORT
    (CLK, CLR: IN STD_LOGIC;
    CON:IN STD_LOGIG_VECTOR(1 DOWNTO 0);
    E: IN STD_LOGIG_VECTOR(3 DOWNTO 0);
    DISPLAY: INOUT STD_LOGIG_VECTOR(6 DOWNTO 0) );
END ENTITY;

