LIBRARY IEEE;
USE IEEE.STD_LOGIC_1164.ALL;
USE IEEE.STD_LOGIC_ARITH.ALL;
USE IEEE.STD_LOGIC_UNSIGNED.ALL;

ENTITY DIV IS PORT
(
    CLK:    IN  STD_LOGIC;
    CLKOUT: OUT STD_LOGIC
);
END ENTITY;

ARCHITECTURE A_DIV OF DIV IS
    SIGNAL CONTADOR: STD_LOGIC_VECTOR(24 DOWNTO 0) := (OTHERS => '0');
    CONSTANT DIVISOR: INTEGER := 27000;
    SIGNAL RELOJ: STD_LOGIC;

    BEGIN
    PROCESS(CLK)
    
        BEGIN 
        IF RISING_EDGE(CLK) THEN
            IF(CONTADOR = DIVISOR) THEN
                CONTADOR <= (OTHERS => '0');
                RELOJ <= NOT RELOJ;
            ELSE
                CONTADOR <= CONTADOR + 1;
            END IF;
        END IF;
    END PROCESS;
    CLKOUT <= RELOJ;
END A_DIV;
    