LIBRARY IEEE;
USE IEEE.STD_LOGIC_1164.ALL;

ENTITY MUX IS PORT
(
    H: IN  STD_LOGIC_VECTOR(6 DOWNTO 0);
    O: IN  STD_LOGIC_VECTOR(6 DOWNTO 0);
    L: IN  STD_LOGIC_VECTOR(6 DOWNTO 0);
    A: IN  STD_LOGIC_VECTOR(6 DOWNTO 0);
    SEL:   OUT STD_LOGIC_VECTOR(3 DOWNTO 0)
);
END ENTITY;

ARCHITECTURE A_CA OF CA IS