LIBRARY IEEE;
USE IEEE.STD_LOGIC_1164.ALL;

ENTITY CA IS PORT
(
    CLKOUT: IN  STD_LOGIC;
    TRAN:   OUT STD_LOGIC_VECTOR(3 DOWNTO 0)
);
END ENTITY;

ARCHITECTURE A_CA OF CA IS
    SIGNAL AUX : STD_LOGIC_VECTOR (3 DOWNTO 0):= "1000";
    BEGIN 
    PROCESS(CLKOUT)
        BEGIN
            IF RISING_EDGE(CLKOUT) THEN
                AUX <= TO_STDLOGICVECTOR(TO_BITVECTOR(AUX)ROR 1);
            END IF;
    END PROCESS;
    TRAN <= AUX;
END A_CA;
    