LIBRARY IEEE;
USE IEEE.STD_LOGIC_1164.ALL;

ENTITY CM IS PORT
(
    DATO, REF: STD_LOGIC_VECTOR (1 DOWNTO 0);
    DIS1: OUT STD_LOGIC_VECTOR (6 DOWNTO 0)
);
END ENTITY;

ARCHITECTURE A_CM OF CM IS
    
    CONSTANT I : STD_LOGIC_VECTOR (6 DOWNTO 0) := "0001001";
    CONSTANT MA: STD_LOGIC_VECTOR (6 DOWNTO 0) := "0001101";
    CONSTANT ME: STD_LOGIC_VECTOR (6 DOWNTO 0) := "0011001";

    BEGIN 
    PROCESS(DATO, REF)
    BEGIN
        IF (DATO = REF) THEN
            DIS1 <=I;
        ELSIF (DATO > REF) THEN
            DIS1 <= MA;
        ELSE
            DIS1 <= ME;
        END IF;
    END PROCESS;
END A_CM;
        