LIBRARY IEEE;
USE IEEE.STD_LOGIC_1164.ALL;

ENTITY CTRL_DISP IS
PORT(
    ENABLE : IN STD_LOGIC;
    D1_IN  : IN STD_LOGIC_VECTOR(6 DOWNTO 0);
    D2_IN  : IN STD_LOGIC_VECTOR(6 DOWNTO 0);
    D3_IN  : IN STD_LOGIC_VECTOR(6 DOWNTO 0);

    D1_OUT : OUT STD_LOGIC_VECTOR(6 DOWNTO 0);
    D2_OUT : OUT STD_LOGIC_VECTOR(6 DOWNTO 0);
    D3_OUT : OUT STD_LOGIC_VECTOR(6 DOWNTO 0)
);
END ENTITY;

ARCHITECTURE A_CTRL_DISP OF CTRL_DISP IS
BEGIN

D1_OUT <= D1_IN WHEN ENABLE='0' ELSE "0000000";
D2_OUT <= D2_IN WHEN ENABLE='0' ELSE "0000000";
D3_OUT <= D3_IN WHEN ENABLE='0' ELSE "0000000";

END A_CTRL_DISP;