LIBRARY IEEE;
USE IEEE.STD_LOGIC_1164.ALL;

ENTITY MUX IS
PORT
(
    A,B,C,D,SEL: IN STD_LOGIC_VECTOR (1 DOWNTO 0);
    DATO: OUT STD_LOGIC_VECTOR (1 DOWNTO 0);
    APAG: OUT STD_LOGIC_VECTOR (13 DOWNTO 0)
);
END ENTITY;

ARCHITECTURE A_MUX OF MUX IS
BEGIN

PROCESS(SEL, A,B,C,D)
BEGIN

CASE SEL IS

WHEN "00" => DATO <=A;
WHEN "01" => DATO <=B;
WHEN "10" => DATO <=C;
WHEN OTHERS => DATO <=D;

END CASE;
APAG <= (OTHERS => '0');

END PROCESS;

END A_MUX;