LIBRARY IEEE;
USE IEEE.STD_LOGIC_1164.ALL;

PACKAGE PAQUETES IS 

COMPONENT MUX 
    PORT (A,B,C,D,SEL: IN STD_LOGIC_VECTOR (1 DOWNTO 0);
    DATO: OUT STD_LOGIC_VECTOR (1 DOWNTO 0)
    );
END COMPONENT;

COMPONENT CM 
    PORT (DATO, REF: IN STD_LOGIC_VECTOR (1 DOWNTO 0);
    DIS1: OUT STD_LOGIC_VECTOR (6 DOWNTO 0)
    );
END COMPONENT;

COMPONENT DEC 
    PORT (ENT: IN STD_LOGIC_VECTOR (1 DOWNTO 0);
    DIS: OUT STD_LOGIC_VECTOR (6 DOWNTO 0)
    );
END COMPONENT;

COMPONENT DIV 
    PORT (CLK: IN STD_LOGIC;
    CLKOUT: OUT STD_LOGIC
    );
END COMPONENT;

COMPONENT CA 
    PORT (CLKOUT: IN STD_LOGIC;
    TRAN: OUT STD_LOGIC_VECTOR (3 DOWNTO 0)
    );
END COMPONENT;

COMPONENT CTRL_DISP
PORT(
    ENABLE : IN STD_LOGIC;
    D1_IN  : IN STD_LOGIC_VECTOR(6 DOWNTO 0);
    D2_IN  : IN STD_LOGIC_VECTOR(6 DOWNTO 0);
    D3_IN  : IN STD_LOGIC_VECTOR(6 DOWNTO 0);

    D1_OUT : OUT STD_LOGIC_VECTOR(6 DOWNTO 0);
    D2_OUT : OUT STD_LOGIC_VECTOR(6 DOWNTO 0);
    D3_OUT : OUT STD_LOGIC_VECTOR(6 DOWNTO 0)
);
END COMPONENT;

END PAQUETES; 