LIBRARY IEEE;
USE IEEE.STD_LOGIC_1164.ALL;
LIBRARY WORK;
USE WORK.PAQUETES.ALL;

ENTITY TOPLEVEL IS
PORT (
A,B,C,D,SEL,REF: IN STD_LOGIC_VECTOR (1 DOWNTO 0);
CLK: IN STD_LOGIC;
ENABLE: IN STD_LOGIC;
TRAN: OUT STD_LOGIC_VECTOR (3 DOWNTO 0);
DIS: OUT STD_LOGIC_VECTOR (6 DOWNTO 0)
);
END ENTITY;

ARCHITECTURE A_TOPLEVEL OF TOPLEVEL IS

SIGNAL DATO: STD_LOGIC_VECTOR (1 DOWNTO 0);
SIGNAL CLKOUT: STD_LOGIC;

SIGNAL DIS1_AUX: STD_LOGIC_VECTOR (6 DOWNTO 0);
SIGNAL DIS2_AUX: STD_LOGIC_VECTOR (6 DOWNTO 0);
SIGNAL DIS3_AUX: STD_LOGIC_VECTOR (6 DOWNTO 0);

BEGIN

U1: MUX PORT MAP (A=>A,B=>B,C=>C,D=>D,SEL=>SEL,DATO=>DATO);

U2: CM PORT MAP (DATO=>DATO,REF=>REF,DIS1=>DIS1_AUX);

U3: DEC PORT MAP (ENT=>DATO,DIS=>DIS2_AUX);

U4: DEC PORT MAP (ENT=>REF,DIS=>DIS3_AUX);

U5: DIV PORT MAP (CLK=>CLK,CLKOUT=>CLKOUT);

U6: CA PORT MAP (CLKOUT=>CLKOUT,TRAN=>TRAN);

-- multiplexado simple de displays
DIS <= DIS1_AUX WHEN TRAN="1000" ELSE
DIS2_AUX WHEN TRAN="0100" ELSE
DIS3_AUX WHEN TRAN="0010" ELSE
"0000000";

END A_TOPLEVEL;
