LIBRARY IEEE;
USE IEEE.STD_LOGIC_1164.ALL;

ENTITY CONTADOR IS PORT
(
    CLK: IN STD_LOGIC;
    CLR: IN STD_LOGIC;
    CON: IN STD_LOGIC_VECTOR (7 DOWNTO 0);
    Q : OUT STD_LOGIC_VECTOR (7 DOWNTO 0);
    Y : OUT STD_LOGIC;
    Z : OUT STD_LOGIC;
);
END ENTITY;

ARCHITECTURE A_CONTADOR OF CONTADOR IS 
    Signal 
    -- Jn = Kn
    Signal J7: STD_LOGIC = (NOT CON) AND Q6  AND Q5  AND Q4  AND Q3  AND Q2  AND Q1  AND Q0;
    Signal J6: STD_LOGIC = (NOT CON) AND Q5  AND Q4  AND Q3  AND Q2  AND Q1  AND Q0;
    Signal J5: STD_LOGIC = (NOT CON) AND Q4  AND Q3  AND Q2  AND Q1  AND Q0;
    Signal J4: STD_LOGIC = (NOT CON) AND Q3  AND Q2  AND Q1  AND Q0;
    Signal J3: STD_LOGIC = (NOT CON) AND Q2  AND Q1  AND Q0;
    Signal J2: STD_LOGIC = (NOT CON) AND Q1  AND Q0;
    Signal J1: STD_LOGIC = (NOT CON) AND Q0;
    Signal J0: STD_LOGIC = (NOT CON);

    -- Flip Flops tipo JK
    
