    LIBRARY IEEE;
USE IEEE.STD_LOGIC_1164.ALL;
ENTITY JK IS
	PORT (CLKOUT,J,K : IN STD_LOGIC;
		Q,NQ : INOUT STD_LOGIC
	);
END ENTITY;
ARCHITECTURE A_JK OF JK IS
BEGIN
	PROCESS (CLKOUT,J,K)
	BEGIN
		IF (CLR = '0') THEN
			Q <= '0';
			NQ <= '1';
		ELSIF RISING_EDGE (CLKOUT) THEN
            Q <= ((NOT K) AND Q)OR(J AND (NOT Q));
            NQ <= NOT(((NOT K) AND Q)OR(J AND (NOT Q)));			
		END IF;
	END PROCESS;
END A_P2;