LIBRARY IEEE;
USE IEEE.STD_LOGIC_1164.ALL;

PACKAGE PAQUETES IS

COMPONENT HOLA
PORT
(
    TRAN    : IN STD_LOGIC_VECTOR(3 DOWNTO 0);
    DISPLAY : OUT STD_LOGIC_VECTOR(6 DOWNTO 0)
);
END COMPONENT;

COMPONENT CA
PORT
(
    CLKOUT : IN STD_LOGIC;
    TRAN   : OUT STD_LOGIC_VECTOR(3 DOWNTO 0)
);
END COMPONENT;

COMPONENT DIV
PORT
(
    CLK:    IN  STD_LOGIC;
    CLKOUT: OUT STD_LOGIC;
    LED    : OUT STD_LOGIC;
    LEDAPAGADO : OUT STD_LOGIC_VECTOR(5 DOWNTO 0)
);
END COMPONENT;

END PAQUETES;